[package]
name = "parasect"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.16.0"
ibig = "0.3.6"
subprocess = "0.2.9"

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"
